export const CONTENT_GET_CONTENT_REQUEST = "CONTENT_GET_CONTENT_REQUEST";
export const CONTENT_GET_CONTENT_SUCCESS = "CONTENT_GET_CONTENT_SUCCESS";
export const CONTENT_GET_CONTENT_FAIL = "CONTENT_GET_CONTENT_FAIL";
